name: Restore cache
description: Restores files from cache, fails on cache miss
author: codequest
inputs:
  path:
    description: A list of files, directories, and wildcard patterns to cache and restore
    required: true
  key:
    description: An explicit key for restoring and saving the cache
    required: true
runs:
  using: node12
  main: dist/index.js
